#!/usr/bin/env bash
#Transfer a file to your server

#Check if the args are up to 4, else display an error message
if [ $# -lt 3 ]; then
	echo "Usage: ${0#./} PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#Store the args in different variables
LOCAL_FILE=$1
IP=$2
USERNAME=$3
PRIVATE_KEY=$4

#If arguments is 3, don't make use of Private key, else, use it.
if [ $# -eq 3 ]; then
	scp -o StrictHostKeyChecking=no "$LOCAL_FILE" "$USERNAME@$IP":~/
else
	scp -o StrictHostKeyChecking=no -i "$PRIVATE_KEY" "$LOCAL_FILE" "$USERNAME@$IP":~/
fi
