#!/usr/bin/env bash
# This script prints "to infinity abd beyond indefinitely"

trap high SIGTERM
high()
{
	echo "I am invincible!!!"
}

i=1
while [ $i -eq 1 ]
do
	echo "To infinity and beyond"
	sleep 2
done
