#!/usr/bin/env bash
# This script changes the ip addresses of localhost andfacebook.com
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new #echo can also be used to do this
# Just echo "127.0.0.2 localhost" > ~/hosts.new and you will also gwt this
echo "8.8.8.8 facebook.com" >> ~/hosts.new #This appends the text
cp -f ~/hosts.new /etc/hosts
